name: Auto-Update Documentation

on:
  push:
    branches:
      - main  # Change if using a different branch
  pull_request:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set Up Node.js (if needed)
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Tree Utility
        run: sudo apt-get install tree -y

      - name: Run Documentation Update Script
        run: |
          chmod +x update_docs.sh
          ./update_docs.sh

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Check for Changes
        run: |
          git add docs/
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

      - name: Commit and Push Changes
        run: |
          git commit -m "Auto-update documentation via GitHub Actions"
          git push origin main

